config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :eats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eat.rb
class Eat < ApplicationRecord
  validates :name, presence:true
  validates :body, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/eats_controller.rb
class EatsController < ApplicationController

  def new
    @eat = Eat.new
  end

  def create
    @eat = Eat.new(eat_params)
    @eat.save
    redirect_to eat_path(@eat.id),notice:'You have created food successfully!'
  end

  def index
    @eats = Eat.all
  end

  def show
    @eat = Eat.find(params[:id])
  end

  def edit
    @eat = Eat.find(params[:id])
  end

  def update
    @eat = Eat.find(params[:id])
    @eat.update(eat_params)
    redirect_to eat_path(@eat.id),notice:'You have updated food successfully!'
  end

  def destroy
    @eat = Eat.find(params[:id])
    @eat.destroy
    redirect_to eats_path
  end

  private


  def eat_params
    params.require(:eat).permit(:name, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eats_helper.rb
module EatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/eats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>Editong Food</h2>
      <%= form_with model: @eat, local:true do |f| %>
      <h2>Name of food</h2>
      <%= f.text_field:name %>
      <h2>Introduction of food</h2>
      <%= f.text_area:body %>
      <%= f.submit"Update Food", class:"btn btn-success" %>
      <% end %>
    </div>
    <%= link_to "Back", eats_path, class:"btn btn-danger" %>
  </div>
</div>

app/views/eats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>index of food</h1>
      <%= link_to "Create Food", new_eat_path, class:"btn btn-success" %>
    </div>
    <div class="col">
     <table>
       <thead>
         <tr>
           <th>name</th>
           <th>introduction</th>
           <th colspan="3"></th>
         </tr>
       </thead>
       <tbody>
         <% @eats.each do |eat| %>
         <tr>
           <td>
             <%= eat.name %>
           </td>
           <td>
             <%= eat.body %>
           </td>
           <td>
             <%= link_to "Show", eat_path(eat.id) ,class:"btn btn-primary" %>
           </td>
           <td>
             <%= link_to "Destroy", eat_path(eat.id),method: :delete, class:"btn btn-danger" %>
           </td>
         </tr>
         <% end %>
       </tbody>
     </table>
    </div>
  </div>
</div>

app/views/eats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Create Food</h1>
    </div>
    <div class="col">
      <%= form_with model: @eat, local:true do |f| %>
      <h2>Name</h2>
      <%= f.text_field:name %>
      <h2>Introduction</h2>
      <%= f.text_area:body %>
      <%= f.submit"Create Food", class:"btn btn-success" %>
      <% end %>
    </div>
    <%= link_to "Back",eats_path, class:"btn btn-danger" %>
  </div>
</div>

app/views/eats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
     <h2>Detail of Food</h2>
     <%= flash[:notice] %>
     <table>
       <thead>
         <tr>
           <th>name</th>
           <th>introduction</th>
         </tr>
       </thead>
       <tbody>
         <tr>
           <td><%= @eat.name %></td>
           <td><%= @eat.body %></td>
         </tr>
       </tbody>
     </table>
     <%= link_to "Edit", edit_eat_path, class:"btn btn-primary" %>
     　｜
     <%= link_to "Back", eats_path, class:"btn btn-danger" %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container-about">
  <div class="row justify-content-around">
    <div class="col-md-7 py-5">
      <h1>Food Dailyとは？？</h1>
      <p>本サイトは、食事に関する事柄などを記載し、投稿するアプリケーションです。</p>
      <p>摂取した食事などを投稿し、日々の生活習慣の改善に役立ててくれたら幸いです！</p>
      <p>ガタガタ言ってないで、筋トレして、食事制限して、引き締まった体で美女と遊べ！！！</p>
    </div>
    <div class="col-md-6 offset-md-4">
      <%= link_to "Go to Top page", root_path ,class:"btn btn-success" %>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class='main'>
  <div class='row justify-content-around'>
    <div class='col-md-6'>
      <h1>Welcome to Food Daily !!!</h1>
      <p>Foos Daily では、食事に関する投稿サイトです。</p>
      <p>日々の生活で摂取する食事やサプリメントなどを記録することで、</p>
      <p>健康面であったり、生活習慣を改善することができます。</p>
    </div>
  </div>
    <div class="col-md-6 offset-md-5">
      <%= link_to "Start", eats_path ,class:"btn btn-success" %>
      <%= link_to "About", home_about_path ,class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
    <p class="footer-text">© All rights reserved by Infratop.Inc.</p>
  </footer>
</html>